name: pregsee
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  bloc: any
  equatable: any
  meta: any


  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.3.4
  rxdart: ^0.28.0
  chewie: ^1.8.5
  video_player: ^2.9.2
  shared_preferences: ^2.3.4
  cloud_firestore: ^5.6.0
  animations: ^2.0.11
  flutter_spinkit: ^5.2.1
  intl: ^0.20.1
  pin_code_fields: ^8.0.1
  razorpay_flutter: ^1.3.7
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  crop_your_image: ^2.0.0
  rive: ^0.13.20
  in_app_review: ^2.0.10
  flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/app_intro/
    - assets/icons/
    - assets/rive/
    - assets/temp/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        
    - family: Iconly-Bold
      fonts:
        - asset: assets/icons/Iconly/Iconly-Bold.ttf
    # - family: Iconly-Broken
    #   fonts:
    #     - asset: assets/icons/Iconly/Iconly-Broken.ttf
    # - family: Iconly-Bulk
    #   fonts:
    #     - asset: assets/icons/Iconly/Iconly-bulk.ttf
    - family: Iconly-Light
      fonts:
        - asset: assets/icons/Iconly/Iconly-light.ttf    

    - family: fontello
      fonts:
        - asset: assets/fonts/fontello.ttf